service: product-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: '3'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-auto-swagger
#  - serverless-openapi-documentation-v2

provider:
  name: aws
  runtime: nodejs12.x
  region: 'eu-west-1'

custom:
  webpack:
    webpackConfig: ./webpack.config.js
  autoswagger:
    typefiles: ['./src/models/product.ts']
    title: 'This is API for Product Service'

package:
  individually: true

functions:
  getProductsList:
    handler: ./src/functions/getProductList.handler
    events:
      - httpApi:
          method: get
          path: /products
          swaggerTags: [ 'Products' ]
          responses:
            200:
              description: 'Return array of products'
              bodyType: 'Product'
  getProductById:
    handler: ./src/functions/getProductById.handler
    events:
      - httpApi:
          method: get
          path: /products/{productId}
          swaggerTags: [ 'Products' ]
          responses:
              200:
                description: 'Return single product'
                bodyType: 'Product'